uosuos_uos:
    pattern:  /uos
    defaults: { _controller: uosuosBundle:Default:uos }
    
uosuosBundle_room:
        resource: "@uosuosBundle/Resources/config/routing/room.yml"
        prefix:   /room
        
uosuosBundle_student:
        resource: "@uosuosBundle/Resources/config/routing/student.yml"
        prefix:   /student 
      
uosuosBundle_employee:
        resource: "@uosuosBundle/Resources/config/routing/employee.yml"
        prefix:   /employee

uosuosBundle_finance:
        resource: "@uosuosBundle/Resources/config/routing/finance.yml"
        prefix:   /finance
        
uosuosBundle_work:
        resource: "@uosuosBundle/Resources/config/routing/work.yml"
        prefix:   /work
        
uosuosBundle_users:
        resource: "@uosuosBundle/Resources/config/routing/users.yml"
        prefix:   /users
        
uosuosBundle_hall:
        resource: "@uosuosBundle/Resources/config/routing/hall.yml"
        prefix:   /hall
      
uosuosBundle_occupy:
        resource: "@uosuosBundle/Resources/config/routing/occupy.yml"
        prefix:   /occupy

